server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://your_host:5433/your_db?prepareThreshold=0&currentSchema=your_schema
    username: your_name
    password: your_pwd
    hikari:
      connection-test-query: SELECT 1

app:
  # cron task run every 2 minutes
  task-interval: 0 */2 * * * *
  lock-at-most-for: 1m
  lock-at-least-for: 1m
  default-lock-at-most-for: 1m
